/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces_Preguntas;

import practicas_dos.CONEX; // Importa la clase CONEX
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;

public class Crear_TEST extends javax.swing.JFrame {

    private CONEX conexion;
    private Connection cx;
    private String idNumClases;
    
    public Crear_TEST(String idNumClases) {
        initComponents();
        conexion = new CONEX();
        cx = conexion.getCx();
        this.idNumClases = idNumClases;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new practicas_dos.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("¡Hola!");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel2.setText("¿Como se llama el Test?");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelRound1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 360, 40));

        jButton1.setText("Empezar a Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 520, 40));
        panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 540, 10));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String testName = jTextField1.getText();
        int testId = guardarTestEnBD(testName);
        if (testId > 0) {
            CrearPreguntas crearPreguntas = new CrearPreguntas(testId); // Pasa el testId a CrearPreguntas
            crearPreguntas.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el test en la base de datos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    private int generarTestIdAleatorio() {
        Random rand = new Random();
        return 100000 + rand.nextInt(900000); // Genera un número aleatorio de 6 cifras
    } 
    
    private boolean testIdExiste(int testId) {
    String query = "SELECT COUNT(*) FROM test WHERE test_id = ?";
    try (PreparedStatement ps = cx.prepareStatement(query)) {
        ps.setInt(1, testId);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt(1) > 0;
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return false;
}
    
    private int guardarTestEnBD(String testName) {
        int testIdAleatorio = generarTestIdAleatorio();
        while (testIdExiste(testIdAleatorio)) {
            testIdAleatorio = generarTestIdAleatorio(); // Genera un nuevo test_id si el actual ya existe
        }
        String query = "INSERT INTO test (test_id, test_name, id_numclases, creation_date) VALUES (?, ?, ?, NOW())";
        try (PreparedStatement ps = cx.prepareStatement(query)) {
            ps.setInt(1, testIdAleatorio); // Usa el testId aleatorio generado
            ps.setString(2, testName);
            ps.setString(3, idNumClases); // Utiliza el idNumClases pasado al constructor
            ps.executeUpdate();
            return testIdAleatorio; // Devuelve el testId generado
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        return -1;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private practicas_dos.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
